name: glow_up
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+3

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  auto_route: ^8.2.0
  auto_route_generator: ^8.0.0
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.5
  rxdart: ^0.27.7
  intl: ^0.19.0
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  cloud_firestore: ^4.9.2
  firebase_core: ^2.16.0
  dio: ^5.3.3
  http: ^1.1.0
  google_fonts: ^5.1.0
  permission_handler: 11.3.1
  in_app_review: ^2.0.9
  image_picker: ^1.1.2
  device_info_plus: ^10.1.0
  camera: ^0.11.0+1
  open_settings_plus: ^0.3.3
  flutter_animation_progress_bar: ^2.3.1
  card_swiper: ^3.0.1
  purchases_flutter: ^6.29.4
  get_storage: ^2.1.1
  blur: ^4.0.0
  url_launcher: ^6.3.0
  path_provider: ^2.1.3
  flutter_local_notifications: ^17.2.1
  share_plus: ^9.0.0
  before_after: ^3.0.0+1
  amplitude_flutter: ^3.7.0
  screenshot: ^3.0.0
  loading_animation_widget: ^1.2.1
  flutter_launcher_icons: ^0.13.1
  image: ^4.2.0
  sensors_plus: ^5.0.1
  flutter_image_compress: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  flutter_gen_runner:
  build_runner:
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: ""
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/onboarding/
    - assets/images/subscription/
    - assets/images/guide/
    - assets/images/guide_info/
    - assets/images/deep_scanning/

  fonts:
    - family: SFPro
      fonts:
        - asset: fonts/SFProDisplay-Regular.ttf
        - asset: fonts/SFProDisplay-Light.ttf


flutter_gen:
  output: lib/generated/
  line_length: 80

  integrations:
    flutter_svg: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
flutter_intl:
  enabled: true